FORMAT: 1A

# SWAPR API

API for the MOOC SWAPR application. This is a super rough draft that's missing a
lot at the moment.

# Group Grades
All operations that have to do with getting grade information.

## Grades [/grades]
A collection of all grades for a particular student.

### List all Grades [GET]
+ Response 200 (application/json)

        [{
            "id": "398572398572398657",
            "title": "Lab 1 Assignment",
            "grade": "89"
        }, {
            "id": "398579528572398930",
            "title": "Lab 2 Assignment",
            "grade": "99"
        }]

## Grade [/grades/{id}]
A single Grade object with all of its details.

+ Parameters
    + id (required, string) ... String `id` of the grade to retrieve.

### Retrieve a Grade [GET]
+ Response 200 (application/json)

        {
            "id": "398572398572398657",
            "title": "Lab 1 Assignment",
            "grade": "89"
        }

# Group Assignments
## Assignments [/assignments]
Assignments related resources of the **SWAPR API**

### List all Assignments [GET]
+ Response 200 (application/json)

        [
            {
                "title": "Lab 1 Video Upload",
                "due": "2014-10-24T21:13:56.703Z",
                "status": "complete",
                "id": "1110471398572098651"
            },
            {
                "title": "Lab 2 Video Upload",
                "due": "2014-10-26T05:13:00.703Z",
                "status": "incomplete",
                "id": "1752945601572987520"
            }
        ]

## Assignment [/assignments/{id}]
A single Assignment object with all its details.

+ Parameters
    + id (required, string) ... String `id` of the assignment to retrieve.

### Retrieve an Assignment [GET]
+ Response 200 (application/json)

        {
            "title": "Lab 1 Video Upload",
            "due": "2014-10-24T21:13:56.703Z",
            "status": "complete",
            "id": "1110471398572098651"
        }

# Group Profile
Profile related resoures of the **SWAPR API**.

## Profile [/profile]
A profile object.

### Retrieve a Profile [GET]

+ Response 200 (application/json)

        {
            "name": "George P. Burdell",
            "major": "Industrial Engineer",
            "tagline": "Loves bones and sticks"
            "profileImage": "http://labsandbuddies.org/IMAGES/clay%20puppy%20profile.JPG"
        }

## Profile [/profile/{id}]
A Profile object.

### Retrieve a Profile [GET]
+ Response 200 (application/json)

        {
            "name": "John Doe"
        }